apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-configmap
data:
  # MYSQL_HOST: host.minikube.internal #this is not working on my pc
  # MYSQL_HOST: localhost
  MYSQL_HOST: mysql.default.svc.cluster.local # replace with your local ip
  MYSQL_USER: auth_user
  MYSQL_DB: auth
  MYSQL_PORT: "3306"
