apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
    # GMAIL_ADDRESS: "testterry2013@gmail.com"
    # GMAIL_PASSWORD: "testyang2013"

    GMAIL_ADDRESS: "frenchduck2013@gmail.com"
    GMAIL_PASSWORD: "kyoe fnso lrsv rspq"