apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
  MAIL163_ADDRESS: __MAIL163_ADDRESS__ #replace with your own email and email app password
  MAIL163_PASSWORD: __MAIL163_PASSWORD__ #replace with your own email and email app password
