apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
type: Opaque
stringData:
  # GMAIL_ADDRESS: "testterry2013@gmail.com"
  # GMAIL_PASSWORD: "testyang2013"

  MAIL163_ADDRESS: "pajkatt2013@163.com"
  MAIL163_PASSWORD: "RGiuXhbpd9yLw69u" #replace with your own email and email app password
